kind: pipeline
name: build-amd64

platform:
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
       from_secret: docker-user
    password: 
       from_secret: docker-pass
    repo: chinodesuuu/drone-volume-cache
    tags: latest
    
---
kind: pipeline
name: build-arm

platform:
  arch: arm

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
       from_secret: docker-user
    password: 
       from_secret: docker-pass
    repo: chinodesuuu/drone-volume-cache
    tags: latest
kind: pipeline
name: build-amd64

platform:
  arch: amd64

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
       from_secret: docker-user
    password: 
       from_secret: docker-pass
    repo: chinodesuuu/drone-volume-cache
    tags: latest
